### ISSUE TITLE
Benchmark compilation fails if java.sql.ResultSet is used

### ISSUE THREAD

**Issue by YulawOne** [sbt/sbt-jmh#192]
Java: 11.0.9.hs-adpt
Scala: 2.13.3
Sbt-jmh: 0.4.0

When I'm trying to compile benchmark that use classes from java.sql package compilation fails with:

```
sbt:scala-benchmarks> jmh:run .*DatabaseBenchmark.*
[info] Compiling 20 Scala sources and 3 Java sources to /projects/scala-benchmarks/target/scala-2.13/classes ...
[info] /projects/scala-benchmarks/src/main/scala/benches/databases/DatabaseBenchmark.scala:64:50: SELECT x.a, x.b, x.c, x.d, x.e, x.f, x.g, x.h, x.i, x.j FROM data x
[info]     def runQuery: List[Data] = TaskEffect.run(run(schema))
[info]                                                  ^
[info] /projects/scala-benchmarks/src/main/scala/benches/databases/DatabaseBenchmark.scala:76:35: SELECT x.a, x.b, x.c, x.d, x.e, x.f, x.g, x.h, x.i, x.j FROM data x
[info]     def runQuery: List[Data] = run(schema)
[info]                                   ^
[warn] 2 deprecations (since 2.13.3); re-run with -deprecation for details
[warn] one warning found
[info] Done compiling.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] running org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator /projects/scala-benchmarks/target/scala-2.13/classes /projects/scala-benchmarks/target/scala-2.13/src_managed/jmh /projects/scala-benchmarks/target/scala-2.13/resource_managed/jmh default
Processing 113 classes from /projects/scala-benchmarks/target/scala-2.13/classes with "reflection" generator
Writing out Java source to /projects/scala-benchmarks/target/scala-2.13/src_managed/jmh and resources to /projects/scala-benchmarks/target/scala-2.13/resource_managed/jmh
Annotation generator had thrown the exception.
java.lang.NoClassDefFoundError: java/sql/ResultSet
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at org.openjdk.jmh.generators.reflection.RFClassInfo.getMethods(RFClassInfo.java:99)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.buildAnnotatedSet(BenchmarkGenerator.java:213)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:77)
	at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.Run.invokeMain(Run.scala:116)
	at sbt.Run.run0(Run.scala:98)
	at sbt.Run.execute$1(Run.scala:72)
	at sbt.Run.$anonfun$run$4(Run.scala:85)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: java.sql.ResultSet
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more



Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-4"
```

**Comment by fsvehla** [comment]
I also ran into this.

**Comment by szegedi** [comment]
This is easily reproducible by checking out https://github.com/twitter/finagle and running:
```
./sbt 'project finagle-benchmark' 'jmh:run com.twitter.finagle.ByteReaderBenchmark'
```
on Java 11. My hunch is that when `Run.run` [constructs a class loader](https://github.com/sbt/sbt/blob/develop/run/src/main/scala/sbt/Run.scala#L76), it uses a `makeLoader` [variant that'll use](https://github.com/sbt/zinc/blob/develop/internal/zinc-classpath/src/main/scala/sbt/internal/inc/classpath/ClasspathUtilities.scala#L98) `instance.loaderLibraryOnly` and in Java 9+ that loader should have (but likely doesn't have) the [platform class loader](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ClassLoader.html#getPlatformClassLoader()) in its parent chain.

**Comment by pawel-wiejacha** [comment]
I get the same error when using openjdk-17 and openjdk-18.

My fix/workaround for this issue can be found here: https://github.com/pawel-wiejacha/sbt-jmh/commit/a916d771b2d75dce3404cce5cba282884f2251c6 where I switched `Run` to `ForkRun`. I'm not sure if it works correctly for every possible configuration, but it fixes the issue for me.
